# Generated by Django 5.1 on 2024-08-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_category_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='quizzes/'),
        ),
    ]
