# Generated by Django 5.1 on 2024-09-03 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='class_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='teacher.class'),
        ),
    ]
