# Generated by Django 5.1 on 2024-09-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_studentclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentClass',
        ),
    ]
