# Generated by Django 5.1 on 2024-09-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_game_userscore_gamequestion_gamechoice_gamesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='game_pictures/'),
        ),
    ]
