# Generated by Django 5.1 on 2024-09-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_game_description_game_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='current_question',
            field=models.IntegerField(default=0),
        ),
    ]
