# Generated by Django 5.1 on 2024-09-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_gamesession_current_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='choices_picture/'),
        ),
    ]
