# Generated by Django 5.1 on 2024-10-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_remove_quizattempt_user_quizattempt_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
