# Generated by Django 5.1 on 2024-10-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_quizattempt_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='user_name',
        ),
    ]
