# Generated by Django 5.1 on 2024-10-06 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0017_remove_quizattempt_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='created_at',
            new_name='attempt_date',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.category'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.quiz'),
        ),
    ]
