# Generated by Django 5.1 on 2024-10-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0020_quizattempt_attempt_date_quizattempt_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='user',
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
