# Generated by Django 5.1 on 2024-10-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0022_fractiongamequestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FractionGameQuestion',
        ),
    ]
