# Generated by Django 5.1 on 2024-10-12 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0023_delete_fractiongamequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FractionGameQuestion',
            fields=[
                ('gamequestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teacher.gamequestion')),
                ('numerator', models.IntegerField()),
                ('denominator', models.IntegerField()),
            ],
            bases=('teacher.gamequestion',),
        ),
    ]
