# Generated by Django 5.1 on 2024-10-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0025_fractiongamesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fractiongamesession',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='fractiongamesession',
            name='total_attempts',
        ),
    ]
