# Generated by Django 5.1 on 2024-10-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0027_fractiongamesession_selected_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fractiongamequestion',
            old_name='denominator',
            new_name='correct_denominator',
        ),
        migrations.RenameField(
            model_name='fractiongamequestion',
            old_name='numerator',
            new_name='correct_numerator',
        ),
    ]
