# Generated by Django 5.1 on 2024-10-13 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0028_rename_denominator_fractiongamequestion_correct_denominator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fractiongamequestion',
            old_name='correct_denominator',
            new_name='denominator',
        ),
        migrations.RenameField(
            model_name='fractiongamequestion',
            old_name='correct_numerator',
            new_name='numerator',
        ),
    ]
