# Generated by Django 5.1 on 2024-10-13 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0029_rename_correct_denominator_fractiongamequestion_denominator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fractiongamequestion',
            old_name='denominator',
            new_name='correct_denominator',
        ),
        migrations.RenameField(
            model_name='fractiongamequestion',
            old_name='numerator',
            new_name='correct_numerator',
        ),
    ]
